[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "shared"
authors = []
dynamic = ["version", "description"]

requires-python = ">=3.10"

dependencies = [
    "python_dateutil >=2.8.2 ,<3.0"
]
