[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "models"
authors = []
dynamic = ["version", "description"]

requires-python = ">=3.10"

dependencies = [
    "pydantic[email] >=1.10.1,<2.0"
]
