name: deploy-prod
run-name: Deploying on production server (by ${{ github.actor }})
on:
  push:
    branches:
      - main
jobs:
  re-deploy:
    runs-on: prod-server
    steps:
      - uses: actions/checkout@v3
        with:
          path: '.'
          clean: false
      - name: Remove old backend app container
        run: ./backend/bin/app-remove-prod-container.sh --skip-if-container-does-not-exist
      - name: Remove old mongo db container
        run: ./backend/bin/mongo-remove-prod-container.sh --skip-if-container-does-not-exist
      - name: Restart backend containers
        run: ./backend/bin/start-prod.sh --run-detached
      - name: Rebuild and restart form website containers
        run: ./form_website/bin/rebuild-and-deploy.sh
