name: deploy-backend
run-name: Deploying backend on production server (by @${{ github.actor }})
on:
  push:
    branches:
      - main
    paths:
      - backend/**
      - shared-bash.sh

jobs:
  re-deploy:
    runs-on: prod-server
    steps:
      - uses: actions/checkout@v3
        with:
          path: '.'
          # We should start from a clean repo in the future
          # and store data somewhere else.
          # TODO: set to true
          clean: false
      - name: Remove old backend app container
        run: ./backend/bin/app-remove-prod-container.sh --skip-if-container-does-not-exist
      - name: Remove old mongo db container
        run: ./backend/bin/mongo-remove-prod-container.sh --skip-if-container-does-not-exist
      - name: Restart backend containers
        run: ./backend/bin/start-prod.sh --run-detached
