# Hack -> see githubs documentation https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks
name: test
on:
  push:
    paths-ignore:
      - backend/**
jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "Dummy workflow to skip tests that are required for backend"'
